# Generated by Django 2.2 on 2021-11-28 22:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0003_auto_20211128_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim Ekle'),
        ),
        migrations.CreateModel(
            name='iletisim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Konu')),
                ('content', ckeditor.fields.RichTextField(max_length=255, verbose_name='İçerik (255) Karakter')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('article_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim Ekle')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar Adı')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
