# Generated by Django 2.2 on 2021-11-29 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20211129_0153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='iletisim',
        ),
    ]
